record_kind_info = {
    'document': {"title": 'Document',
                 "nested_colspan": 4,
                 "record_types": ['D'],
                 "table_columns": [
                   ('pmid', "PMID"),
                   ("link", "Link"),
                 ],
                 "ref_by_kinds": ['extract'],
                 "ref_kinds": []},
    'extract': {"title": 'Document Extract',
                "nested_colspan": 6,
                "record_types": ['S', 'T'],
                 "table_columns": [
                   ("record_type", "Extract Type"),
                   ('id', "ID"),
                   ("document", "Document"),
                   ("content", "Text / Table Ref."),
                ],
                "ref_by_kinds": ['crule', 'vrule'],
                "ref_kinds": ['document']},
    'unit': {"title": "Unit",
             "nested_colspan": 7,
             "record_types": ['U'],
             "table_columns": [
               ('id', "ID"),
               ("kind", "Type Kind"),
               ("base_type", "Base Type"),
               ("enumerating", "Enum."),
               ("multi", "Multi"),
               ("definition", "Definition"),
               ("symbol", "Symbol"),
               ("description", "Description"),
             ],
             "ref_by_kinds": ['unit', 'attribute', 'model'],
             "ref_kinds": ['unit']},
    'attribute': {"title": "Attribute",
                  "nested_colspan": 8,
                  "record_types": ['A'],
                  "table_columns": [
                    ('id', "ID"),
                    ("unit", "Unit"),
                    ("mode", "Measurement Mode"),
                    ("reference", "Reference"),
                    ("location_type", "Location Type"),
                    ("location_label", "Location Label"),
                  ],
                  "ref_by_kinds": ['vrule', 'crule'],
                  "ref_kinds": ['unit']},
    'group': {"title": "Group",
              "nested_colspan": 6,
              "record_types": ['G'],
              "table_columns": [
                ('id', "ID"),
                ("type", "Type"),
                ("name", "Name"),
                ("definition", "Definition"),
              ],
              "ref_by_kinds": ['group', 'vrule', 'crule'],
              "ref_kinds": ['group']},
    'model': {"title": "Model",
              "nested_colspan": 5,
              "record_types": ['M'],
              "table_columns": [
                ('unit', "Unit"),
                ('resource_id', "Resource"),
                ("model_id", "Model ID"),
                ("model_name", "Model Name"),
              ],
              "ref_by_kinds": [],
              "ref_kinds": ['unit']},
    'vrule': {"title": "Value Expectation Rule",
              "nested_colspan": 8,
              "record_types": ['V'],
              "table_columns": [
                ('id', "ID"),
                ('source', "Sources"),
                ("attribute", "Attribute"),
                ("group", "Group"),
                ("group_portion", "Group Portion"),
                ("operator", "Operator"),
                ("reference", "Reference"),
              ],
              "ref_by_kinds": [],
              "ref_kinds": ['attribute', 'group', 'extract']},
    'crule': {"title": "Comparative Expectation Rule",
              "nested_colspan": 9,
              "record_types": ['C'],
              "table_columns": [
                ('id', "ID"),
                ('source', "Sources"),
                ("attribute", "Attribute"),
                ("group1", "Group 1"),
                ("group1_portion", "Group&nbsp;1 Portion"),
                ("operator", "Operator"),
                ("group2", "Group 2"),
                ("group2_portion", "Group&nbsp;2 Portion"),
              ],
              "ref_by_kinds": [],
              "ref_kinds": ['attribute', 'group', 'extract']},
}
