record_kind_info = {
    'document': {"title": 'Document',
                 "nested_colspan": 4,
                 "record_types": ['D'],
                 "ref_by_kinds": ['extract'],
                 "ref_kinds": []},
    'extract': {"title": 'Document Extract',
                "nested_colspan": 6,
                "record_types": ['S', 'T'],
                "ref_by_kinds": ['crule', 'vrule'],
                "ref_kinds": ['document']},
    'unit': {"title": "Unit",
             "nested_colspan": 7,
             "record_types": ['U'],
             "ref_by_kinds": ['unit', 'attribute', 'model'],
             "ref_kinds": ['unit']},
    'attribute': {"title": "Attribute",
                  "nested_colspan": 8,
                  "record_types": ['A'],
                  "ref_by_kinds": ['vrule', 'crule'],
                  "ref_kinds": ['extract', 'unit']},
    'group': {"title": "Group",
              "nested_colspan": 6,
              "record_types": ['G'],
              "ref_by_kinds": ['group', 'vrule', 'crule'],
              "ref_kinds": ['group']},
    'model': {"title": "Model",
              "nested_colspan": 5,
              "record_types": ['M'],
              "ref_by_kinds": [],
              "ref_kinds": ['unit']},
    'vrule': {"title": "Value Expectation Rule",
              "nested_colspan": 8,
              "record_types": ['V'],
              "ref_by_kinds": [],
              "ref_kinds": ['attribute', 'group', 'extract']},
    'crule': {"title": "Comparative Expectation Rule",
              "nested_colspan": 9,
              "record_types": ['C'],
              "ref_by_kinds": [],
              "ref_kinds": ['attribute', 'group', 'extract']},
}
